
services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    environment:
      POSTGRES_DB: scouts
      POSTGRES_USER: scouts
      POSTGRES_PASSWORD: scouts # testing only
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: