openapi: 3.0.3
info:
  title: Scout Groups API
  description: API for managing scout groups within the organization
  version: 1.0.0

paths:
  /groups:
    get:
      summary: Get all groups
      description: Retrieves a list of all scout groups
      operationId: getAllGroups
      responses:
        '200':
          description: List of groups retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
    post:
      summary: Create a new group
      description: Creates a new scout group
      operationId: createGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
      responses:
        '201':
          description: Group created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'

  /groups/{id}:
    get:
      summary: Get group by ID
      description: Retrieves a specific group by its ID
      operationId: getGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Group found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '404':
          description: Group not found

    put:
      summary: Update group
      description: Updates an existing group
      operationId: updateGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
      responses:
        '200':
          description: Group updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '404':
          description: Group not found

    delete:
      summary: Delete group
      description: Deletes a group by its ID
      operationId: deleteGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Group deleted successfully
        '404':
          description: Group not found

components:
  schemas:
    Group:
      type: object
      properties:
        id:
          type: integer
          format: int64
        version:
          type: integer
          format: int64
        name:
          type: string
          minLength: 1
      required:
        - name

    GroupRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
      required:
        - name
